### PR TITLE
Milestone5

### PR DESCRIPTION
**Pull request by Paul-Clue**
## What I Did:
- I implemented the handleClick function in the App, ButtonPanel, and Button, components.
- I placed the onClick event handler on all of the buttons to allow the handleClick function to fire if any button is pressed.

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @Paul-Clue**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] all of the operations except for addition and subtraction are not working.  Please make sure to fix them.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @Paul-Clue**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] There are still some logical errors that need to be fixed. here a video of them https://www.loom.com/share/dd25c7d507b6479093f9205d5294361d


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️ 
@Paul-Clue well done for implementing the suggested changes from the previous Code Reviewerhow ever changes required
### highlights
handling errors when numbers divide by 0 👍🏻 
Addiction button functioning well 👍🏻 
### improve

- [ ] kindly make the percentage(%) button works automatic onClick 
- [ ] At times when I click the division button prompt `TypeError: a.div is not a function` when working with the division button.

### once specific changes are made kindly request for another review

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @Paul-Clue**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
